Export types to make them reusable for other packages
gardener/dependency-watchdog pull request #33
Opened 2021-06-18 11:49 UTC by rfranzke

**What this PR does / why we need it**:
Export types to make them reusable for other packages

/invite @amshuman-kr 
/squash

**Release note**:

```feature developer
Export types in `pkg/restarter` and `pkg/scaler` to make them reusable for other packages.
```

2021-06-21 03:24 UTC, amshuman-kr approved these changes
Thanks @rfranzke! Do you plan to reuse them elsewhere?

/lgtm

2021-06-21 06:11 UTC, amshuman-kr requested changes
@rfranzke `make check` is failing with the following logs. Could you please address them. Apart from that, LGTM.
```
pkg/restarter/types.go:47:6: exported type Service should have comment or be unexported
pkg/restarter/types.go:51:6: exported type DependantPods should have comment or be unexported
pkg/scaler/types.go:61:6: exported type ProbeDependants should have comment or be unexported
pkg/scaler/types.go:67:6: exported type ProbeConfig should have comment or be unexported
pkg/scaler/types.go:77:6: exported type ProbeDetails should have comment or be unexported
pkg/scaler/types.go:81:6: exported type DependantScaleDetails should have comment or be unexported
```

2021-06-21 06:34 UTC, rfranzke commented
> Do you plan to reuse them elsewhere?

Yes, as part of gardener/gardener#2754, the Helm charts will be eliminated in favor of Golang struct usages, and it would be great if the DWD config can be handled similarly.

> Could you please address them

Could you recommend reasonable doc strings (maybe directly via GitHub suggestions)? I'm not too into all this code.

2021-06-21 11:31 UTC, amshuman-kr requested changes
I have added the suggested comments for the now public types.

2021-06-21 11:31 UTC, amshuman-kr commented on pkg/scaler/types.go
> +type ProbeConfig struct {
```suggestion
// ProbeConfig struct captures the details for probing a Kubernetes apiserver.
type ProbeConfig struct {
```

2021-06-21 11:31 UTC, amshuman-kr commented on pkg/scaler/types.go
> +type ProbeDetails struct {
```suggestion
// ProbeDetails captures the kubeconfig secret details to probe a Kubernetes apiserver.
type ProbeDetails struct {
```

2021-06-21 11:31 UTC, amshuman-kr commented on pkg/scaler/types.go
> +type DependantScaleDetails struct {
```suggestion
// DependantScaleDetails has the details about the dependant scale sub-resource.
type DependantScaleDetails struct {
```

2021-06-22 05:20 UTC, amshuman-kr approved these changes
/lgtm

2021-06-22 05:21 UTC, merged